
package services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ContraseniaIncorrectaException", targetNamespace = "http://services/")
public class ContraseniaIncorrectaException_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ContraseniaIncorrectaException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ContraseniaIncorrectaException_Exception(String message, ContraseniaIncorrectaException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ContraseniaIncorrectaException_Exception(String message, ContraseniaIncorrectaException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: services.ContraseniaIncorrectaException
     */
    public ContraseniaIncorrectaException getFaultInfo() {
        return faultInfo;
    }

}
