
package services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ProductoNoExisteException", targetNamespace = "http://services/")
public class ProductoNoExisteException_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ProductoNoExisteException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ProductoNoExisteException_Exception(String message, ProductoNoExisteException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ProductoNoExisteException_Exception(String message, ProductoNoExisteException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: services.ProductoNoExisteException
     */
    public ProductoNoExisteException getFaultInfo() {
        return faultInfo;
    }

}
